### ISSUE TITLE
DO NOT OPEN NEW ISSUES

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-Client-for-MC-1.8.X#2330]
**We are no longer using the GitHub Issue Tracker. Please use the [Wurst Feedback App](https://feedback.wurst-client.tk/) instead.**

From now on, the [Wurst Feedback App](https://feedback.wurst-client.tk/) will fully replace this Issue Tracker. Any Issues opened after this one will be closed, probably without even being read.

So if you want to suggest something or report a bug or whatever, then this is definitely the wrong place to do that. As I said before, I'm not even reading the Issues anymore. Just because there are so many of them being added every day.

If you haven't heard of the whole [Feedback App](https://feedback.wurst-client.tk/) stuff yet, it's basically a place where you can submit feedback about the Wurst Client, the Wurst website, etc., similar to the Issue Tracker, but then other people can vote on your feedback.

For instance, if you suggest a new feature for Wurst and you get a lot of votes for it, I can see that a lot of people want that feature too and I will make it a high priority to add that feature.

Whereas if you just type in a bunch of spam or make a low-quality duplicate of an existing suggestion, then you probably won't get any votes for that and I probably won't even see it, much less consider using it.

And by the way, the only reason why I haven't disabled the Issue Tracker is so that people can still read the old Issues (e.g. the ones I linked to in the changelogs).

**Comment by beppe9000** [comment]
Even for bugs/crash reports ??

**Comment by Alexander01998** [comment]
> Even for bugs/crash reports ??

Yes.

**Comment by labcraft59** [comment]
I would rather if you could comment on the feedback... It would be better that way... ALSO, it would be nice if you could see how many people voted on things...

**Comment by DataPools** [comment]
Problem is, your issue will get lost in the endless amounts of issues posted every day.

**Comment by beppe9000** [comment]
BtW I still think the GitHub Issue Traker is good for actual issues.

**Comment by im4nthony** [comment]
What if I am asking a question and I need a response? I wanted to know how to use the .give command as a forge mod :/

**Comment by Alexander01998** [comment]
> What if I am asking a question and I need a response?

You can use the comments section of the [Wurst News](https://www.wurst-client.tk/) or the [Wurst YouTube Channel](https://www.wurst-client.tk/youtube).

> I wanted to know how to use the .give command as a forge mod :/

Wurst is not compatible to Forge.

**Comment by DataPools** [comment]
The feedback app isn't that good for issues :/ I like the forum like feel of the issue tracker

**Comment by null-dev** [comment]
Why not you wait until the feedback app is production ready before forcing people to use it? It's currently way to buggy for me to use. (I can't even create an account) I know there is spam here but many other open source projects use this issue tracker with no problem. Just specify a required issue format instead and close any issues that do not conform to the format.

**Comment by Alexander01998** [comment]
> Why not you wait until the feedback app is production ready before forcing people to use it? It's currently way to buggy for me to use. (I can't even create an account)

Production ready is not the same as bug free. There are plenty of people that have created their account and new ones are coming in every day. Therefore I certainly won't stop it just because one user failed to create an account.

> I know there is spam here but many other open source projects use this issue tracker with no problem. Just specify a required issue format instead and close any issues that do not conform to the format.

Doing that was extremely time-consuming due to huge amounts of spam being posted at all times. I had very specific contributing guidelines here but barely anyone even bothered to read them. Worst of all: GitHub doesn't have a vote button, making the feedback almost completely useless.

It seems that some people here are having quite crazy fantasies about GitHub Issues. Please remember that I have seen the Issues and know that they were horrible, while you have never seen the Issues and only imagine that they were good.

> EDIT: Actually, use the issue tracker for issues and the feedback app for new features.

No.

**Comment by DataPools** [comment]
What about the reply feature? I liked that a lot, because if there was spam, then the users of the community could handle it. Wurst used to be a community and now that has all been taken away

**Comment by Alexander01998** [comment]
> What about the reply feature? I liked that a lot, because if there was spam, then the users of the community could handle it.

Comments have never removed a piece of spam, they only created more of it. People commented on random Issues about things that were completely off-topic, rather than using them to improve the Issues as intended.

Worst of all, most of the people who did that called the Issue Tracker a forum and used that as an excuse for spamming. Even now that it is closed, lots of people tell me to "bring the forum back". I haven't deleted the forum, the forum never existed. This was an Issue Tracker that had been heavily abused as a forum.

> Wurst used to be a community and now that has all been taken away

The Wurst community has actually grown massively after removal of the Issue Tracker. Just take a look at some of the **actual community sites** like the [Wurst YouTube channel](https://www.wurst-client.tk/youtube) or the [Wurst Disqus page](https://disqus.com/home/forums/wurst-client/) (a.k.a. the Wurst-Client.tk comments).

Here's another thing for you to look at: https://github.com/Wurst-Imperium/Wurst-Client/blob/696b9bc6b804e76cb0f040fb0c5fd5581836e0f1/CONTRIBUTING.md

Those are the contributing guidelines of the Issue Tracker. They clearly say:

> Don't include opinions or judgements, only information.

This is another thing that shows my clear intention of using this place as an Issue Tracker and nothing else. And no, I didn't add this later. You can see at the top right that this part was added on March 29, during the time when the Issue Tracker was just getting started. It has never ever EVER been a forum, a community site or anything like that. It was an Issue Tracker that has been heavily abused. And the Feedback App is the new, abuse-proof Issue Tracker.

**Comment by null-dev** [comment]
Since this is your view on things, isn't there an option in GitHub to
disable the issue tracker completely?

What about the reply feature? I liked that a lot, because if there was
spam, then the users of the community could handle it.

Comments have never removed a piece of spam, they only created more of it.
People commented on random Issues about things that were completely
off-topic, rather than using them to improve the Issues as intended.

Worst of all, most of the people who did that called the Issue Tracker a
forum and used that as an excuse for spamming. Even now that it is closed,
lots of people tell me to "bring the forum back". I haven't deleted the
forum, the forum never existed. This was an Issue Tracker that had been
heavily abused as a forum.

Wurst used to be a community and now that has all been taken away

The Wurst community has actually grown massively after removal of the Issue
Tracker. Just take a look at some of the *actual community sites* like
the Wurst
YouTube channel <https://www.wurst-client.tk/youtube> or the Wurst Disqus
page <https://disqus.com/home/forums/wurst-client/> (a.k.a. the
Wurst-Client.tk comments).

Here's another thing for you to look at:
https://github.com/Wurst-Imperium/Wurst-Client/blob/696b9bc6b804e76cb0f040fb0c5fd5581836e0f1/CONTRIBUTING.md

Those are the contributing guidelines of the Issue Tracker. They clearly
say:

Don't include opinions or judgements, only information.

This is another thing that shows my clear intention of using this place as
an Issue Tracker and nothing else. And no, I didn't add this later. You can
see at the top right that this part was added on March 29, during the time
when the Issue Tracker was just getting started. It has never ever EVER
been a forum, a community site or anything like that. It was an Issue
Tracker that has been heavily abused. And the Feedback App is the new,
abuse-proof Issue Tracker.

—
Reply to this email directly or view it on GitHub
<https://github.com/Wurst-Imperium/Wurst-Client/issues/2330#issuecomment-159027841>
.

**Comment by DataPools** [comment]
The feedback app is not useful at all, because it is spammed heavily as well with people wanting impossible features to Wurst. The good suggestions are all lost in the noise.

**Comment by null-dev** [comment]
Why not we have a community vote?

**Comment by ThisTestUser** [comment]
Very true that. There are duplicates that are being posted ad impossible features requested, like "ForceOP for 1.8.8" or other impossible things.

**Comment by Alexander01998** [comment]
> Since this is your view on things, isn't there an option in GitHub to
> disable the issue tracker completely?

The only reason I didn't disable it is so that people can still read the old suggestions and bug reports. If there was a way to disable opening new Issues without hiding the existing ones, I would totally do that.

> The feedback app is not useful at all, because it is spammed heavily as well with people wanting impossible features to Wurst.

The same thing happened here.

> The good suggestions are all lost in the noise.

This happened here, but doesn't happen in the Feedback App since the good suggestions are getting votes and are ranking much higher than the bad ones.

> YouTube comments are not a community.

Look at frikken PewDiePie and tell me that YouTube is not a community.

> People wanting answers could easily get them, now they have to comment on the YouTube channel, where only the most popular "liked" comments are able to be seen.

This makes it look like you have never even seen my YouTube channel, because it couldn't be further from the truth. The Wurst community is asking & answering a lot more questions on my YouTube channel than it ever did on the Issue Tracker.

Likes are especially helpful here, as they automatically filter out boring, useless and/or spammy comments while highlighting the interesting, useful and funny comments. Frequently asked questions get a lot of votes and rise to the top, so that people can see the answer to those questions without even having to ask them.

YouTube is meant to be a community site, the GitHub Issue Tracker isn't, neither is the Feedback App.

> In the Issue Tracker there is the option for issues to be "closed" and an issue would be "done with".

Same with the Feedback App.

> There were also tags where we could see the current status of a suggestion.

The Feedback App uses categories and sub-categories for that.

> Also, since the Issue Tracker is not being used (Currently) I do not believe the Contributing.MD apply here

I showed you an old version of the contributing guidelines that applied here when the Issue Tracker was just getting started (as I said). The new contributing guidelines do not cover Issues anymore. Technically, "DO NOT OPEN NEW ISSUES" are the new contributing guidelines for Issues.

**Comment by DataPools** [comment]
What about the impossible ones like ForceOP 1.8.8 everyone will vote it up, but it is clearly impossible, but all the people who have no knowledge about programming upvote it. With the reply feature, people can say it is impossible.

**Comment by avydrado** [comment]
my country banned from wurst-clinet.tk?

**Comment by pokeball99** [comment]
@avydrado it *could* be that your contry blocks .tk domains due it .tk being known to be used as malware and such (let me see if there is a list of contries with .tk domains banned or not,will edit this then)

**Comment by liach** [comment]
You can find a lot of proxy softwares on github to connect to .tk sites. By the way, what is your country?

**Comment by avydrado** [comment]
Russia

**Comment by avydrado** [comment]
@pokeball99 site work now
